"""HTML email templates for FinXCloud notifications."""

from __future__ import annotations


def status_report_html(
    date: str,
    tasks: list[dict],
    team_summary: dict[str, dict],
    next_priorities: list[str],
) -> str:
    """Generate an HTML status report email.

    Args:
        date: Report date string (e.g. "2026-04-06").
        tasks: List of dicts with keys: id, title, owner, status, next_steps.
        team_summary: Dict of agent_name -> {tasks_done: int, summary: str}.
        next_priorities: List of next priority strings.
    """
    task_rows = ""
    for t in tasks:
        status_color = {
            "done": "#22c55e",
            "in_progress": "#3b82f6",
            "in-progress": "#3b82f6",
            "todo": "#f59e0b",
            "to-do": "#f59e0b",
            "blocked": "#ef4444",
        }.get(t.get("status", "").lower().replace("_", "-"), "#6b7280")

        task_rows += f"""
        <tr>
            <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;">{t.get('id', '')}</td>
            <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;">{t.get('title', '')}</td>
            <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;">{t.get('owner', '')}</td>
            <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;">
                <span style="background:{status_color};color:white;padding:2px 8px;border-radius:4px;font-size:12px;">
                    {t.get('status', '')}
                </span>
            </td>
            <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;">{t.get('next_steps', '')}</td>
        </tr>"""

    team_rows = ""
    for name, info in team_summary.items():
        team_rows += f"""
        <tr>
            <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;font-weight:bold;">{name}</td>
            <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;text-align:center;">{info.get('tasks_done', 0)}</td>
            <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;">{info.get('summary', '')}</td>
        </tr>"""

    next_items = "".join(f"<li style='margin-bottom:4px;'>{p}</li>" for p in next_priorities)

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;color:#1f2937;max-width:900px;margin:0 auto;padding:20px;">

<div style="background:linear-gradient(135deg,#1e40af,#3b82f6);color:white;padding:24px 32px;border-radius:8px 8px 0 0;">
    <h1 style="margin:0;font-size:24px;">AICloud Strategist — Daily Status Report</h1>
    <p style="margin:4px 0 0;opacity:0.9;">{date}</p>
</div>

<div style="border:1px solid #e5e7eb;border-top:none;padding:24px 32px;border-radius:0 0 8px 8px;">

<h2 style="color:#1e40af;font-size:18px;margin-top:0;">Task Status</h2>
<table style="width:100%;border-collapse:collapse;font-size:14px;">
    <thead>
        <tr style="background:#f3f4f6;">
            <th style="padding:8px 12px;text-align:left;border-bottom:2px solid #d1d5db;">#</th>
            <th style="padding:8px 12px;text-align:left;border-bottom:2px solid #d1d5db;">Task</th>
            <th style="padding:8px 12px;text-align:left;border-bottom:2px solid #d1d5db;">Owner</th>
            <th style="padding:8px 12px;text-align:left;border-bottom:2px solid #d1d5db;">Status</th>
            <th style="padding:8px 12px;text-align:left;border-bottom:2px solid #d1d5db;">Next Steps</th>
        </tr>
    </thead>
    <tbody>{task_rows}
    </tbody>
</table>

<h2 style="color:#1e40af;font-size:18px;">Team Summary</h2>
<table style="width:100%;border-collapse:collapse;font-size:14px;">
    <thead>
        <tr style="background:#f3f4f6;">
            <th style="padding:8px 12px;text-align:left;border-bottom:2px solid #d1d5db;">Team Member</th>
            <th style="padding:8px 12px;text-align:center;border-bottom:2px solid #d1d5db;">Tasks Done</th>
            <th style="padding:8px 12px;text-align:left;border-bottom:2px solid #d1d5db;">Summary</th>
        </tr>
    </thead>
    <tbody>{team_rows}
    </tbody>
</table>

<h2 style="color:#1e40af;font-size:18px;">Next Priorities</h2>
<ul style="font-size:14px;line-height:1.6;">{next_items}</ul>

<h2 style="color:#1e40af;font-size:18px;">Blockers</h2>
<p style="font-size:14px;color:#22c55e;">None.</p>

<hr style="border:none;border-top:1px solid #e5e7eb;margin:24px 0;">
<p style="font-size:12px;color:#9ca3af;text-align:center;">
    Generated by FinXCloud — AICloud Strategist Internal Tooling
</p>
</div>
</body>
</html>"""
